package cz.cuni.mff.aspect.evolution.levels.pmp.evaluators

import cz.cuni.mff.aspect.evolution.levels.pmp.metadata.PMPLevelMetadata
import cz.cuni.mff.aspect.mario.GameStatistics
import cz.cuni.mff.aspect.mario.level.MarioLevel
import io.jenetics.Optimize

/** Interface for evaluators of levels generated by Probabilistic Multipass level generator. */
interface PMPLevelEvaluator<F> {

    /**
     * Computes the evaluation and returns its value.
     * @param levels the generated levels.
     * @param metadata metadata of the generated levels.
     * @param gameStatistics gameplay statistics of some agent playing the levels.
     */
    operator fun invoke(levels: List<MarioLevel>, metadata: List<PMPLevelMetadata>, gameStatistics: List<GameStatistics>): F

    /** Specifies whether this evaluator's value should be maximized or minimized. */
    val optimize: Optimize

}
