package cz.cuni.mff.aspect.evolution.levels.chunks.metadata

import cz.cuni.mff.aspect.mario.level.DirectMarioLevel
import cz.cuni.mff.aspect.mario.level.MarioLevel

/** Represents chunks metadata of a level as generated by [cz.cuni.mff.aspect.evolution.levels.chunks.PCLevelGenerator]. */
data class ChunksLevelMetadata(
    val chunks: List<ChunkWithHeight>,
    val entities: Array<IntArray>
) {

    /** Generates Super Mario level given level metadata represented by this entity. */
    fun createLevel(): MarioLevel {
        val tiles: Array<ByteArray> = this.createTiles()
        return DirectMarioLevel(tiles, this.entities)
    }

    /** Generates Super Mario level tiles given level metadata represented by this entity. */
    fun createTiles(): Array<ByteArray> {
        val tilesList: MutableList<ByteArray> = mutableListOf()

        for ((chunk, level) in this.chunks) {
            tilesList.addAll(chunk.generate(level))
        }

        return tilesList.toTypedArray()
    }

}
